services:
    solr:
        restart: always
        image: dbgrs/solr
        build:
            context: .
            dockerfile: ./SolrServer/Dockerfile
        ports:
            - 127.0.0.1:8983:8983
        volumes:
            - /var/solr/data:/var/solr/data/data
    tika:
        image: apache/tika:latest
        restart: always
        ports:
            - 127.0.0.1:9998:9998

volumes:
    solr: